apiVersion: apps/v1
kind: Deployment

metadata:
  name: my_reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
      
  template:
    metadata:
      labels:
        app: react-app
        
    spec:
      containers:
      - name: my_reactapp
        image: hothaifaz11/react-app
        ports:
        - containerPort: 3000
